cert-manager-timeout: 30m0s
overridesFolder: HOME/.tkg/overrides
NODE_STARTUP_TIMEOUT: 20m
BASTION_HOST_ENABLED: "true"
providers:
  - name: cluster-api
    url: HOME/.tkg/providers/cluster-api/v0.3.10/core-components.yaml
    type: CoreProvider
  - name: aws
    url: HOME/.tkg/providers/infrastructure-aws/v0.5.5/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: HOME/.tkg/providers/infrastructure-vsphere/v0.7.1/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: azure
    url: HOME/.tkg/providers/infrastructure-azure/v0.4.8/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: tkg-service-vsphere
    url: HOME/.tkg/providers/infrastructure-tkg-service-vsphere/v1.0.0/unused.yaml
    type: InfrastructureProvider
  - name: kubeadm
    url: HOME/.tkg/providers/bootstrap-kubeadm/v0.3.10/bootstrap-components.yaml
    type: BootstrapProvider
  - name: kubeadm
    url: HOME/.tkg/providers/control-plane-kubeadm/v0.3.10/control-plane-components.yaml
    type: ControlPlaneProvider
  - name: docker
    url: HOME/.tkg/providers/infrastructure-docker/v0.3.10/infrastructure-components.yaml
    type: InfrastructureProvider
images:
    all:
        repository: registry.tkg.vmware.run/cluster-api
    cert-manager:
        repository: registry.tkg.vmware.run/cert-manager
        tag: v0.16.1_vmware.1
release:
    version: v1.2.0
VSPHERE_SERVER: vcsa-01.haas-226.pez.pivotal.io
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_PASSWORD: <encoded:YXB1ZWFicHFCNGdYbjRFeWZDIQ==>
VSPHERE_DATACENTER: /Datacenter
VSPHERE_DATASTORE: /Datacenter/datastore/Datacenter/datastore/LUN01
VSPHERE_NETWORK: Extra
VSPHERE_RESOURCE_POOL: /Datacenter/host/Cluster/Resources/tkg
VSPHERE_FOLDER: /Datacenter/vm/tkg/tkg-mgmt
# VSPHERE_TEMPLATE will be autodetected based on the kubernetes version. Please use VSPHERE_TEMPLATE only to override this behavior
VSPHERE_TEMPLATE: /Datacenter/vm/tkg/Templates/photon-3-kube-v1.19.1-vmware.2
VSPHERE_HAPROXY_TEMPLATE: /Datacenter/vm/tkg/Templates/
VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBr28LJzPLZ0EezNbfk524sufy3KD/sMy3J29gsOjcOfhDJIW7nT0raozmkSkmFhshcBidmY4uYHS0T9gwQXdmnFgb0V39+a+4Uyw3zdHwbtGIZU5bEQnAbSK9Is46TT49jL2eQ1fIO64+1bY4Lvq2UGGmRD0xPjQF6Bo0yWYHt0qXM5ezh9/YojqC4pJA5T5HC8U5rQF+zeHMDrRWsF7Lj48fm9QbIZW4JwC6MPJ0xx5Z3Ynve99wFu/NtUxrneRE8vL+YxPG3qjnSFLMMtROvxF2/ZvGtK70fEQSwCdFP0UGBwOgTUYQaKFs14GbQ0whWVZpHpYf4Mt+d80dmM2EtedaY/WT30dM0rQJfPDeq8bHHlYgOva7F/QWK734GZHJG5fLvonMBkH37EkectBCAKja1Spi1lQm3fcb2Hx31+7VsXHbq5973HygeVjZcyhwX2/8iOtD6bHy2Drlw6abAZX5uewK8Bp8V5Aw9oow9x/0g2At1RQKSco63DtHIaMT6KUplaD+834sY4EgxjeZaYjfrD8uE+Pb1cphq3qO8pW1IergIHJEk7kH0ch2P/KnPdfSU2b+A/BRAlNVGmCxo4PkYA90+hXLEEQF3IgsH4s1fQFj7fR79X1O5vwAujDyfCRYLqMfjExSKIQ+KQX6aMORbWwd07IyGl3Ob3h4VQ==
    jsheth@pivotal.io"
SERVICE_CIDR: 100.64.0.0/13
CLUSTER_CIDR: 100.96.0.0/11
VSPHERE_WORKER_DISK_GIB: "30"
VSPHERE_WORKER_NUM_CPUS: "2"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_DISK_GIB: "30"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "1"
VSPHERE_CONTROL_PLANE_MEM_MIB: "2048"
VSPHERE_HA_PROXY_DISK_GIB: "30"
VSPHERE_HA_PROXY_NUM_CPUS: "1"
VSPHERE_HA_PROXY_MEM_MIB: "2048"
tkg:
    regions:
      - name: tkg-mgmt
        context: tkg-mgmt-admin@tkg-mgmt
        file: HOME/.kube-tkg/config
        status: Success
        isCurrentContext: false
    current-region-context: tkg-mgmt-admin@tkg-mgmt
